### ISSUE TITLE
Update database to use Singleton connection

### ISSUE THREAD

**Issue by jebidiah252** [jebidiah252/usu-gdsf#6]
We'll want to update the current database connection to use a singleton pattern. This shouldn't be too much of a change, but will involve some refactoring.

**Comment by rohit078689** [comment]
i can try this

**Comment by mpt777** [comment]
There is an example of this in the UNO repor

**Comment by mpt777** [comment]
I might be mistaken, but aren't the databases already using a singleton pattern? We are instantiating a database based on an environment variable, and all databases are just just interfaces with the same functionality (connect, disconnect, getallgames...).
I may totally be wrong, but I just want to clarify

**Comment by jebidiah252** [comment]
I think the idea was to initially have the database connection be static and then setup the singleton pattern around that. I believe that this issue can be closed out.
